### PR TITLE
implement subjects client

### PR DESCRIPTION
**Pull request by phasewalk1**

### CODE REVIEW

**Comment by MrBeeMovie** [comment]
Hey @phasewalk1 ! I have been focusing on other projects/work lately. Would you like to take ownership of this repository?

**Comment by phasewalk1** [comment]
> 

Hey @MrBeeMovie, no worries. I'd love to take on ownership and keep it alive!

**Comment by MrBeeMovie** [comment]
Hi @phasewalk1, please make an account on crates.io or give me a link to your account so I can transfer crate ownership over to you. Sorry for late response.

**Comment by phasewalk1** [comment]
Hey @MrBeeMovie, here's the link to my crates.io profile:
https://crates.io/users/phasewalk1

**Comment by MrBeeMovie** [comment]
@phasewalk1 you are added as an owner for openlibrary-rs on crates.io. You need to rename your forked version of this repository in order for me to transfer the github repository ownership over to you.

**Comment by phasewalk1** [comment]
@MrBeeMovie all set!

**Comment by MrBeeMovie** [comment]
Hey @phasewalk1 , you can't have a fork for me to transfer ownership. Let's merge this PR. Then you can delete the fork and I will transfer ownership.

**Comment by MrBeeMovie** [comment]
Hey @phasewalk1 , you can't have a fork for me to transfer ownership. Let's merge this PR. Then you can delete the fork and I will transfer ownership.

**Comment by phasewalk1** [comment]
Hey @MrBeeMovie no problem, the fork is deleted

**Comment by MrBeeMovie** [comment]
@phasewalk1 transfer has been initiated. If you have any problems let me know.

**Pull request merged**
